Hospice/Hospice/Controllers/PatientCardCommentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Hospice.Domain.Abstract;
using Hospice.Domain.Entities;
using Hospice.Infrastructure.Attributes;

namespace Hospice.Controllers
{
    [CustomAuthorize]
    public class PatientCardCommentController : Controller
    {
        private IViewCommentRepository viewCommentRepository;
        public PatientCardCommentController(IViewCommentRepository viewCommentRepo)
        {
            viewCommentRepository = viewCommentRepo;
        }

        public PartialViewResult GetComments()
        {
            int itemId = Hospice.Infrastructure.Helpers.SessionHelper.GetUICurrentSettings().SelectedCommentItemId;
            string viewName = Hospice.Infrastructure.Helpers.SessionHelper.GetUICurrentSettings().SelectedCommentViewName;

            ViewBag.Message = viewName + itemId;

            return PartialView(viewCommentRepository.ViewComment.Where(p => p.ParentViewName == viewName && p.fldId == itemId).ToList());
        }

        public PartialViewResult AddComment()
        {
            return PartialView(new ViewComment());
        }


        [HttpPost]
        public ActionResult AddComment(ViewComment model)
        {
            if (ModelState.IsValid)
            {
                ViewComment comment = new ViewComment();
                comment.Content = model.Content;
                comment.Author = Hospice.Infrastructure.Helpers.SessionHelper.GetUserSettings().AuthenticatedUser.CurrentUserInfo.DisplayName;
                comment.fldId = Hospice.Infrastructure.Helpers.SessionHelper.GetUICurrentSettings().SelectedCommentItemId;
                comment.ParentViewName = Hospice.Infrastructure.Helpers.SessionHelper.GetUICurrentSettings().SelectedCommentViewName;
                comment.Date = DateTime.Now;
                viewCommentRepository.SaveViewComment(comment);

            }

            return RedirectToAction(Hospice.Infrastructure.Helpers.SessionHelper.GetUICurrentSettings().SelectedCommentViewName, Hospice.Infrastructure.Helpers.SessionHelper.GetUICurrentSettings().SelectedCommentControllerName, new { fldId = Hospice.Infrastructure.Helpers.SessionHelper.GetUICurrentSettings().SelectedCommentItemId });

        }
    }
}

Hospice/Hospice/Controllers/PatientCardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Hospice.Domain.Abstract;
using Hospice.Domain.Entities;
using Hospice.Infrastructure.Helpers;
using Hospice.Models;
using Hospice.Infrastructure.Attributes;

namespace Hospice.Controllers
{
    [CustomAuthorize]
    public class PatientCardController : Controller
    {
        private IPatientHSRepository patientHSRepository;
        private IPatientHDRepository patientHDRepository;
        private IPatientWfDoctorDiscriminatorHDRepository patientWfDoctorDiscriminatorHDRepository;
        private IPatientMedicalHistoryHSRepository patientMedicalHistoryHSRepository;
        private IPatientRegisteryHDRepository patientRegisteryHDRepository;
        private IPatientVisitNurseHSRepository patientVisitNurseHSRepository;
        private ITblInstanceWorkflowsRepository tblInstanceWorkflowsRepository;
        private IPatientRegisteryRegisteryHSRepository patientRegisteryRegisteryHSRepository;
        private IPatientWfPsychologistDiscriminatorHSRepository patientWfPsychologistDiscriminatorHSRepository;
        private IPatientWfPsychologistDiscriminatorHDRepository patientWfPsychologistDiscriminatorHDRepository;
        private IPatientWfPhysiotherapistDiscriminatorHSRepository patientWfPhysiotherapistDiscriminatorHSRepository;
        private IPatientWfPhysiotherapistDiscriminatorHDRepository patientWfPhysiotherapistDiscriminatorHDRepository;
        private IPatientCommissionedHireHDRepository patientCommissionedHireHDRepository;

        public PatientCardController(
            IPatientHSRepository patientHSRepo, IPatientHDRepository patientHDRepo, 
            IPatientWfDoctorDiscriminatorHDRepository patientWfDoctorDiscriminatorHDRepo,
            IPatientMedicalHistoryHSRepository patientMedicalHistoryHSRepo,
            IPatientRegisteryHDRepository patientRegisteryHDRepo,
            IPatientVisitNurseHSRepository patientVisitNurseHSRepo,
            ITblInstanceWorkflowsRepository tblInstanceWorkflowsRepo,
            IPatientRegisteryRegisteryHSRepository patientRegisteryRegisteryHSRepo,
            IPatientWfPsychologistDiscriminatorHSRepository patientWfPsychologistDiscriminatorHSRepo,
            IPatientWfPsychologistDiscriminatorHDRepository patientWfPsychologistDiscriminatorHDRepo,
            IPatientWfPhysiotherapistDiscriminatorHSRepository patientWfPhysiotherapistDiscriminatorHSRepo,
            IPatientWfPhysiotherapistDiscriminatorHDRepository patientWfPhysiotherapistDiscriminatorHDRepo,
            IPatientCommissionedHireHDRepository patientCommissionedHireHDRepo
            )
        {
            patientHSRepository = patientHSRepo;
            patientHDRepository = patientHDRepo;
            patientWfDoctorDiscriminatorHDRepository = patientWfDoctorDiscriminatorHDRepo;
            patientMedicalHistoryHSRepository = patientMedicalHistoryHSRepo;
            patientRegisteryHDRepository = patientRegisteryHDRepo;
            patientVisitNurseHSRepository = patientVisitNurseHSRepo;
            tblInstanceWorkflowsRepository = tblInstanceWorkflowsRepo;
            patientRegisteryRegisteryHSRepository = patientRegisteryRegisteryHSRepo;
            patientWfPsychologistDiscriminatorHSRepository = patientWfPsychologistDiscriminatorHSRepo;
            patientWfPsychologistDiscriminatorHDRepository = patientWfPsychologistDiscriminatorHDRepo;
            patientWfPhysiotherapistDiscriminatorHSRepository = patientWfPhysiotherapistDiscriminatorHSRepo;
            patientWfPhysiotherapistDiscriminatorHDRepository = patientWfPhysiotherapistDiscriminatorHDRepo;
            patientCommissionedHireHDRepository = patientCommissionedHireHDRepo;
        }

        public ActionResult Index()
        {
            MenuHelper.SetCurrentCardMenuItem(0);
            MenuHelper.SetCurrentTeleMenuItem(0);
            MenuHelper.SetCurrentCardMiddleMenuItem(0);
            MenuHelper.SetCurrentMainAppMenuItem(1);

            var model = new PatientSearchModel
            {
                HospiceTypes = GetHospiceTypes()
            };

            return View(model);
        }

        public ActionResult PatientCardPatientSearchResults(PatientSearchModel model)
        {
            List<Hospice.Models.PatientCardPatientModel> patients = new List<PatientCardPatientModel>();
  

            if (model.FirstName != null && model.LastName == null && model.PESEL == null)
            {
                if (model.SelectedHospiceTypeId == 1 || model.SelectedHospiceTypeId == 0)
                foreach(Hospice.Domain.Entities.PatientHS patient in patientHSRepository.PatientsHS.Where(p => p.txtImiepacjenta.StartsWith(model.FirstName)).OrderBy( ob => ob.txtNazwiskopacjenta))
                {
                    
                    patients.Add(new PatientCardPatientModel(patient.fldId, patient.txtImiepacjenta, patient.txtNazwiskopacjenta, patient.PESEL, true));
                }

                if (model.SelectedHospiceTypeId == 2 || model.SelectedHospiceTypeId == 0)
                foreach (Hospice.Domain.Entities.PatientHD patient in patientHDRepository.PatientsHD.Where(p => p.txtImiepacjenta.StartsWith(model.FirstName)).OrderBy(ob => ob.txtNazwiskopacjenta))
                {
                    patients.Add(new PatientCardPatientModel(patient.fldId, patient.txtImiepacjenta, patient.txtNazwiskopacjenta, patient.PESEL, false));
                }
                return View("PatientCardPatientSearchResults", patients.OrderBy(ob => ob.txtNazwiskopacjenta).ToList());

                /*
                if (model.SelectedHospiceTypeId == 1) //stacjonarne
                    return View("PatientCardPatientSearchResultsHS", patientHSRepository.PatientsHS.Where(p => p.txtImiepacjenta.StartsWith(model.FirstName)).OrderBy( ob => ob.txtNazwiskopacjenta));
                else //domowe
                    return View("PatientCardPatientSearchResultsHD", patientHDRepository.PatientsHD.Where(p => p.txtImiepacjenta.StartsWith(model.FirstName)).OrderBy(ob => ob.txtNazwiskopacjenta));
                 */
            }
            else
                if (model.FirstName == null && model.LastName != null && model.PESEL == null)
                {
                    if (model.SelectedHospiceTypeId == 1 || model.SelectedHospiceTypeId == 0)
                    foreach (Hospice.Domain.Entities.PatientHS patient in patientHSRepository.PatientsHS.Where(p => p.txtNazwiskopacjenta.StartsWith(model.LastName)).OrderBy(ob => ob.txtNazwiskopacjenta))
                    {
                        patients.Add(new PatientCardPatientModel(patient.fldId, patient.txtImiepacjenta, patient.txtNazwiskopacjenta, patient.PESEL, true));
                    }

                    if (model.SelectedHospiceTypeId == 2 || model.SelectedHospiceTypeId == 0)
                    foreach (Hospice.Domain.Entities.PatientHD patient in patientHDRepository.PatientsHD.Where(p => p.txtNazwiskopacjenta.StartsWith(model.LastName)).OrderBy(ob => ob.txtNazwiskopacjenta))
                    {
                        patients.Add(new PatientCardPatientModel(patient.fldId, patient.txtImiepacjenta, patient.txtNazwiskopacjenta, patient.PESEL, false));
                    }
                    return View("PatientCardPatientSearchResults", patients.OrderBy(ob => ob.txtNazwiskopacjenta).ToList());
                    /*
                    if (model.SelectedHospiceTypeId == 1) //stacjonarne
                        return View("PatientCardPatientSearchResultsHS", patientHSRepository.PatientsHS.Where(p => p.txtNazwiskopacjenta.StartsWith(model.LastName)).OrderBy(ob => ob.txtNazwiskopacjenta));
                    else //domowe
                        return View("PatientCardPatientSearchResultsHD", patientHDRepository.PatientsHD.Where(p => p.txtNazwiskopacjenta.StartsWith(model.LastName)).OrderBy(ob => ob.txtNazwiskopacjenta));
                     */
                }
                else
                    if (model.FirstName == null && model.LastName == null && model.PESEL != null)
                    {
                        if (model.SelectedHospiceTypeId == 1 || model.SelectedHospiceTypeId == 0)
                        foreach (Hospice.Domain.Entities.PatientHS patient in patientHSRepository.PatientsHS.Where(p => p.PESEL.StartsWith(model.PESEL)).OrderBy(ob => ob.txtNazwiskopacjenta))
                        {
                            patients.Add(new PatientCardPatientModel(patient.fldId, patient.txtImiepacjenta, patient.txtNazwiskopacjenta, patient.PESEL, true));
                        }

                        if (model.SelectedHospiceTypeId == 2 || model.SelectedHospiceTypeId == 0)
                        foreach (Hospice.Domain.Entities.PatientHD patient in patientHDRepository.PatientsHD.Where(p => p.PESEL.StartsWith(model.PESEL)).OrderBy(ob => ob.txtNazwiskopacjenta))
                        {
                            patients.Add(new PatientCardPatientModel(patient.fldId, patient.txtImiepacjenta, patient.txtNazwiskopacjenta, patient.PESEL, false));
                        }
                        return View("PatientCardPatientSearchResults", patients.OrderBy(ob => ob.txtNazwiskopacjenta).ToList());

                        /*
                        if (model.SelectedHospiceTypeId == 1) //stacjonarne
                            return View("PatientCardPatientSearchResultsHS", patientHSRepository.PatientsHS.Where(p => p.PESEL.StartsWith(model.PESEL)).OrderBy(ob => ob.txtNazwiskopacjenta));
                        else //domowe
                            return View("PatientCardPatientSearchResultsHD", patientHDRepository.PatientsHD.Where(p => p.PESEL.StartsWith(model.PESEL)).OrderBy(ob => ob.txtNazwiskopacjenta));
                         */
                    }
                    else
                        if (model.FirstName != null && model.LastName != null && model.PESEL != null)
                        {

Hospice/Hospice/Views/PatientCardDoctor/DisplayPatientDoctorVisitCardHD.cshtml
@model Hospice.Domain.Entities.PatientDoctorVisitCardHD
@{
    Layout = "~/Views/Shared/_LayoutForPrinting.cshtml";
}
@Html.DisplayForModel()

Hospice/Hospice/Views/PatientCardDoctor/DisplayPatientEstablishmentOfMedicalHistoryHD.cshtml
@model Hospice.Domain.Entities.PatientEstablishmentOfMedicalHistoryHD
@{
    Layout = "~/Views/Shared/_LayoutForPrinting.cshtml";
}
@Html.DisplayForModel()

Hospice/Hospice/Views/PatientCardDoctor/DisplayPatientFullExaminationHD.cshtml
@model Hospice.Domain.Entities.PatientFullExaminationHD
@{
    Layout = "~/Views/Shared/_LayoutForPrinting.cshtml";
}
@Html.DisplayForModel()

Hospice/Hospice/Views/PatientCardDoctor/DisplayPatientInterventionHD.cshtml
@model Hospice.Domain.Entities.PatientInterventionHD
@{
    Layout = "~/Views/Shared/_LayoutForPrinting.cshtml";
}

@Html.DisplayForModel()

Hospice/Hospice/Views/PatientCardDoctor/DisplayPatientMedicalHisotryHS.cshtml
@model Hospice.Domain.Entities.PatientMedicalHistoryHS
@{
    Layout = "~/Views/Shared/_LayoutForPrinting.cshtml";
}
@Html.DisplayForModel()
@{Html.RenderAction("GetComments", "PatientCardComment");} 

Hospice/Hospice/Views/PatientCardDoctor/DisplayPatientOrdersForNursesHD.cshtml
@model Hospice.Domain.Entities.PatientOrdersForNursesHD

@{
    Layout = "~/Views/Shared/_LayoutForPrinting.cshtml";
}
@Html.DisplayForModel()

Hospice/Hospice/Views/PatientCardDoctor/DisplayPatientOrdersForNursesHS.cshtml
@model Hospice.Domain.Entities.PatientOrdersForNursesHS

@{
    Layout = "~/Views/Shared/_LayoutForPrinting.cshtml";
}
@Html.DisplayForModel()

Hospice/Hospice/Views/PatientCardDoctor/DisplayPatientOrdersOtherHD.cshtml
@model Hospice.Domain.Entities.PatientOrdersOtherHD

@{
    Layout = "~/Views/Shared/_LayoutForPrinting.cshtml";
}
@Html.DisplayForModel()

Hospice/Hospice/Views/PatientCardDoctor/DisplayPatientQualifyingVisitHD.cshtml
@model Hospice.Domain.Entities.PatientQualifyingVisitHD

@{
    Layout = "~/Views/Shared/_LayoutForPrinting.cshtml";
}
@Html.DisplayForModel()

Hospice/Hospice/Views/PatientCardDoctor/DisplayPatientReferralForExaminationHD.cshtml
@model Hospice.Domain.Entities.PatientReferralForExaminationHD

@{
    Layout = "~/Views/Shared/_LayoutForPrinting.cshtml";
}

@Html.DisplayForModel()

Hospice/Hospice/Views/PatientCardDoctor/DisplayPatientReferralForExaminationHS.cshtml
@model Hospice.Domain.Entities.PatientReferralForExaminationHS

@{
    Layout = "~/Views/Shared/_LayoutForPrinting.cshtml";
}
@Html.DisplayForModel()

Hospice/Hospice/Views/PatientCardDoctor/DisplayPatientReferralToPsychologistHD.cshtml
@model Hospice.Domain.Entities.PatientReferralToPsychologistHD
@{
    Layout = "~/Views/Shared/_LayoutForPrinting.cshtml";
}
@Html.DisplayForModel()

Hospice/Hospice/Views/PatientCardDoctor/DisplayPatientReferralToPsychotherapistHD.cshtml
@model Hospice.Domain.Entities.PatientReferralToPsychotherapistHD

@{
    Layout = "~/Views/Shared/_LayoutForPrinting.cshtml";
}
@Html.DisplayForModel()

Hospice/Hospice/Views/PatientCardDoctor/PatientCardPatientMedicalHistoryDoctorHD.cshtml
@model Hospice.Models.SeededCategories

@{
    ViewBag.Title = "Platforma FHO";
}


<div class="row">
    <div class="col-md-12">
        <section id="">
            @{Html.RenderAction("_PatientCardSelectedPatientMenuMiddleTeleHistory", "PatientCard");}
            @{Html.RenderAction("_PatientCardSelectedPatientSelected", "PatientCard");}
            @{Html.RenderAction("_PatientCardSelectedPatientMenu", "PatientCard");}
        </section>
        <section id="">
            @Html.Partial("_PatientCardMedicalHistoryTreeCategories", Model)
        </section>
    </div>
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}